import {lazy,Suspense,useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Search,X,ChevronRight,ArrowUpRight,Compass,Bookmark,Check,Ship,Footprints,Bike,Share2,BookOpen,MapPin,SlidersHorizontal,Info,ArrowLeft,Leaf,Sun,Mountain,Waves,Landmark,Utensils,CircleHelp,CheckCircle2,Globe,ChevronUp,ChevronDown} from 'lucide-react';
import poiData from '../data/poi/verified.json';
import islandData from '../data/islands.json';
import topicData from '../data/topics.json';
import stats from '../data/stats.json';
import type {Context,Island,Mode,Poi,Season,Topic} from './model';
import {directionsUrl,matchesSearch,matchesIsland,orderedSections,publicPoi,recommend,requiresFerry} from './engine';
import type {ViewRequest} from './MapView';
const MapView=lazy(()=>import('./MapView'));
const pois=(poiData as Poi[]).filter(publicPoi),islands=islandData as Island[],topics=topicData as Topic[];
const categories=['絶景 / 展望','歴史 / 文化財','神社 / 寺','アート','海 / 海岸 / 海水浴場','自然','サイクリング','体験','食','買い物','宿泊','港 / 船','橋','公園','キャンプ','産業景観','島の暮らし','季節限定','隠れスポット'];
function initialState(){const params=new URLSearchParams(location.hash.slice(1));return {poi:pois.some(p=>p.id===params.get('poi'))?params.get('poi'):null,island:islands.some(i=>i.name===params.get('island'))?params.get('island')!:'all',q:params.get('q')||'',category:categories.includes(params.get('category')||'')?params.get('category')!:'all',terrain:params.get('terrain')!=='0',deep:params.get('deep')==='1',topic:topics.some(t=>t.id===params.get('topic'))?params.get('topic'):null,season:(['春','夏','秋','冬'].includes(params.get('season')||'')?params.get('season'):currentSeason()) as Season,mode:(['walking','cycling','ferry'].includes(params.get('mode')||'')?params.get('mode'):'walking') as Mode};}
function currentSeason():Season{const m=new Date().getMonth()+1;return m>=3&&m<=5?'春':m>=6&&m<=8?'夏':m>=9&&m<=11?'秋':'冬';}
function readSaved():string[]{try{return JSON.parse(localStorage.getItem('tripscape-saved')||'[]').filter((id:unknown)=>typeof id==='string'&&pois.some(p=>p.id===id));}catch{return [];}}
const iconFor=(p:Poi)=>p.categories.includes('食')?Utensils:p.categories.includes('海 / 海岸 / 海水浴場')?Waves:p.categories.includes('歴史 / 文化財')?Landmark:p.categories.includes('絶景 / 展望')?Mountain:MapPin;
const ModeIcon={walking:Footprints,cycling:Bike,ferry:Ship};
const modeNames={walking:'徒歩',cycling:'自転車',ferry:'船'};

export default function App(){
  const initial=useRef(initialState()).current;
  const [selected,setSelected]=useState<string|null>(initial.poi),[island,setIsland]=useState(initial.island),[q,setQ]=useState(initial.q),[category,setCategory]=useState(initial.category),[terrain,setTerrain]=useState(initial.terrain),[deep,setDeep]=useState(initial.deep);
  const [view,setView]=useState<ViewRequest>({kind:initial.poi?'poi':initial.island!=='all'?'island':'overview',id:initial.poi||initial.island,nonce:0});
  const [season,setSeason]=useState<Season>(initial.season),[mode,setMode]=useState<Mode>(initial.mode),[saved,setSaved]=useState(readSaved),[savedOnly,setSavedOnly]=useState(false),[history,setHistory]=useState<string[]>([]);
  const [topic,setTopic]=useState<string|null>(initial.topic),[filtersOpen,setFiltersOpen]=useState(false),[sheet,setSheet]=useState<'compact'|'detail'|'deep'>(initial.deep?'deep':'detail'),[about,setAbout]=useState(false),[status,setStatus]=useState('地図を読み込み中'),[toast,setToast]=useState('');
  const [origin,setOrigin]=useState<{lat:number;lng:number}|undefined>(),[originType,setOriginType]=useState<'port'|'current'>('port');
  const dialog=useRef<HTMLDialogElement>(null);
  const p=pois.find(p=>p.id===selected);
  const context:Context={island,season,mode,hour:new Date().getHours(),history,categories:category==='all'?[]:[category]};
  const visible=useMemo(()=>pois.filter(p=>(island==='all'||p.island===island)&&(category==='all'||p.categories.includes(category))&&(!savedOnly||saved.includes(p.id))&&(!topic||p.related_topics.includes(topic))&&matchesSearch(p,q)),[island,category,q,savedOnly,saved,topic]);
  const selectedIsland=islands.find(i=>i.name===island);
  const islandSuggestions=q.trim()?islands.filter(i=>matchesIsland(i,q)):[];
  const suggestions=p?recommend(p,pois,context):[];
  const speak=useCallback((text:string)=>setToast(text),[]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{try{localStorage.setItem('tripscape-saved',JSON.stringify(saved));}catch{speak('保存できません。この画面を開いている間は利用できます。');}},[saved,speak]);
  useEffect(()=>{
    const params=new URLSearchParams();if(selected)params.set('poi',selected);if(island!=='all')params.set('island',island);if(q)params.set('q',q);if(category!=='all')params.set('category',category);if(!terrain)params.set('terrain','0');if(deep)params.set('deep','1');if(topic)params.set('topic',topic);params.set('season',season);if(mode!=='walking')params.set('mode',mode);
    window.history.replaceState(null,'',`${location.pathname}${location.search}${params.size?'#'+params:''}`);
  },[selected,island,q,category,terrain,deep,topic,season,mode]);
  useEffect(()=>{const onHash=()=>{const s=initialState();setSelected(s.poi);setIsland(s.island);setQ(s.q);setCategory(s.category);setTerrain(s.terrain);setDeep(s.deep);setTopic(s.topic);setSeason(s.season);setMode(s.mode);setSheet(s.deep?'deep':'detail');setView(v=>({kind:s.poi?'poi':s.island!=='all'?'island':'overview',id:s.poi||s.island,nonce:v.nonce+1}));};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);},[]);
  useEffect(()=>{if(about)dialog.current?.showModal();else dialog.current?.close();},[about]);
  function select(id:string){const target=pois.find(p=>p.id===id);if(!target)return;setSelected(id);setIsland('all');setQ('');setCategory('all');setTopic(null);setSavedOnly(false);setDeep(false);setSheet('detail');setFiltersOpen(false);setView(v=>({kind:'poi',id,nonce:v.nonce+1}));setHistory(h=>[...h.filter(x=>x!==id),id].slice(-20));}
  function chooseIsland(name:string){setIsland(name);setSelected(null);setDeep(false);setQ('');setCategory('all');setTopic(null);setFiltersOpen(false);setView(v=>({kind:name==='all'?'overview':'island',id:name,nonce:v.nonce+1}));}
  function closeDetail(){setSelected(null);setDeep(false);setSheet('detail');}
  function reset(){setQ('');setCategory('all');setTopic(null);setSavedOnly(false);chooseIsland('all');}
  function toggleSave(id:string){setSaved(old=>old.includes(id)?old.filter(s=>s!==id):[...old,id]);}
  async function share(){try{await navigator.clipboard.writeText(location.href);speak('この地図のURLをコピーしました。');}catch{speak('URLをコピーできません。アドレスバーのURLで共有できます。');}}
  function locate(){
    if(!navigator.geolocation){speak('このブラウザーは現在地取得に対応していません。');return;}
    speak('現在地を確認しています。');
    navigator.geolocation.getCurrentPosition(({coords})=>{
      setOrigin({lat:coords.latitude,lng:coords.longitude});setOriginType('current');
      if(coords.longitude<133.05||coords.longitude>133.43||coords.latitude<34.10||coords.latitude>34.34){speak('現在地は地図の範囲外です。航路を含む公式アクセス案内を確認してください。');return;}
      setView(v=>({kind:'location',coordinates:[coords.longitude,coords.latitude],nonce:v.nonce+1}));speak('現在地を表示しました。位置は保存しません。');
    },()=>speak('現在地を取得できませんでした。位置情報の許可や端末の設定を確認してください。'),{timeout:10000,maximumAge:60000});
  }
  const TopicIcon=mode==='ferry'?Ship:mode==='cycling'?Bike:Footprints;
  const activeTopic=topics.find(t=>t.id===topic);
  return <div className="app-shell">
    <a className="skip-link" href="#search-input">検索へ移動</a>
    <header className="topbar">
      <button className="brand" onClick={reset} aria-label="上島町の地図を全域表示"><img src={`${import.meta.env.BASE_URL}favicon.svg`} alt=""/><span>KAMIJIMA <b>TRIPSCAPE</b><small>3D ISLAND EXPLORER</small></span></button>
      <div className="header-center"><span className="tiny-dot"/> EHIME · SETOUCHI <span className="header-rule"/> 上島町の観光図鑑</div>
      <nav><button className={savedOnly?'active':''} onClick={()=>{setSavedOnly(!savedOnly);setSelected(null);}} aria-pressed={savedOnly}><Bookmark size={16}/>旅のしおり<span className="count-badge">{saved.length}</span></button><button onClick={share} aria-label="地図のURLをコピー"><Share2 size={17}/><span className="desktop-label">共有</span></button><button onClick={()=>setAbout(true)} aria-label="この地図について"><Info size={18}/></button></nav>
    </header>
    <main>
      <Suspense fallback={<div className="map-loading"><Compass size={32}/><p>島々の地図をひらいています</p></div>}><MapView pois={pois} visible={visible} islands={islands} selected={selected} view={view} mobileSheet={sheet} onPoi={select} onIsland={chooseIsland} terrain={terrain} onTerrain={setTerrain} onStatus={setStatus} onLocate={locate}/></Suspense>
      <aside className={`explorer ${filtersOpen?'mobile-open':''}`} aria-label="地点の検索と絞り込み">
        <div className="explorer-heading"><span className="eyebrow">FIND YOUR ISLAND</span><button className="mobile-close icon-button" onClick={()=>setFiltersOpen(false)} aria-label="検索パネルを閉じる"><X size={18}/></button><h1>島の日々を、<br/>地図から。</h1><p>気になる場所から、<br/>その先の物語へ。</p></div>
        <div className="search-field"><Search size={17}/><input id="search-input" aria-label="観光スポットを検索" placeholder="桜、塩、海辺…" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button onClick={()=>setQ('')} aria-label="検索をクリア"><X size={14}/></button>}</div>
        <section className="filter-section"><div className="section-label">島をえらぶ <span>08 ISLANDS</span></div><div className="island-grid"><button className={island==='all'?'active':''} onClick={()=>chooseIsland('all')}>すべての島</button>{islands.map(i=><button key={i.id} className={island===i.name?'active':''} onClick={()=>chooseIsland(i.name)}>{i.name}<span>{stats.by_island[i.name as keyof typeof stats.by_island]}</span></button>)}</div></section>
        <section className="filter-section"><div className="section-label">興味から探す <button onClick={()=>{setCategory('all');setTopic(null);setQ('');setSavedOnly(false);}}>リセット</button></div><div className="category-grid">{['絶景 / 展望','歴史 / 文化財','海 / 海岸 / 海水浴場','自然','食','アート'].map((c,i)=>{const Icon=[Mountain,Landmark,Waves,Leaf,Utensils,Globe][i];return <button key={c} className={category===c?'active':''} onClick={()=>setCategory(category===c?'all':c)} aria-pressed={category===c}><Icon size={14}/>{['絶景','歴史・文化','海辺','自然','食','アート'][i]}</button>;})}</div><select aria-label="すべての観光カテゴリ" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">すべてのカテゴリ</option>{categories.map(c=><option key={c}>{c}</option>)}</select></section>
        <section className="travel-context"><div><Sun size={15}/><select aria-label="旅の季節" value={season} onChange={e=>setSeason(e.target.value as Season)}>{(['春','夏','秋','冬'] as Season[]).map(s=><option key={s}>{s}</option>)}</select><span>の旅</span></div><div className="mode-buttons" role="group" aria-label="移動手段">{(['walking','cycling','ferry'] as Mode[]).map(m=>{const Icon=ModeIcon[m];return <button key={m} aria-label={modeNames[m]} aria-pressed={mode===m} className={mode===m?'active':''} onClick={()=>setMode(m)}><Icon size={16}/></button>;})}</div></section>
        {activeTopic&&<div className="topic-banner"><button onClick={()=>setTopic(null)} aria-label="テーマを解除"><X size={14}/></button><strong>{activeTopic.name}</strong><p>{activeTopic.summary}</p></div>}
        <div className="results-heading"><span>{q||category!=='all'||topic||savedOnly?'検索結果':'地図にある場所'}</span><b aria-live="polite">{visible.length}<small>件</small></b></div>
        <div className="results" aria-label="観光スポット一覧">{islandSuggestions.length>0&&<section className="island-suggestions" aria-label="検索に関連する島"><h2>関連する島</h2>{islandSuggestions.map(i=><div key={i.id}><button className="result-item" onClick={()=>chooseIsland(i.name)}><span className="result-icon"><Compass size={17}/></span><span className="result-copy"><small>島の公式紹介から</small><strong>{i.name}</strong><small>{i.summary}</small></span><ChevronRight size={15}/></button><a href={i.official_url} target="_blank" rel="noopener noreferrer">{i.name}の公式ガイド <ArrowUpRight size={12}/></a></div>)}</section>}{visible.map(p=>{const Icon=iconFor(p);return <button className={`result-item ${selected===p.id?'selected':''}`} key={p.id} onClick={()=>select(p.id)}><span className="result-icon"><Icon size={17}/></span><span className="result-copy"><small>{p.island} · {p.categories[0].split(' / ')[0]}</small><strong>{p.name}</strong></span><ChevronRight size={15}/></button>;})}{visible.length===0&&islandSuggestions.length===0&&<div className="empty-results"><Search size={24}/><h2>条件に合う場所はありません</h2><p>未確認地点は地図に表示していません。<br/>別の島やテーマから探してみてください。</p><button onClick={reset}>条件をリセット</button></div>}</div>
        <button className="research-note" onClick={()=>setAbout(true)}><CheckCircle2 size={14}/><span>出典と確認日を、すべての場所に。</span><ArrowUpRight size={13}/></button>
      </aside>
      <div className="mobile-search"><div className="search-field"><Search size={17}/><input aria-label="モバイルで観光スポットを検索" placeholder="桜、塩、海辺…" value={q} onChange={e=>{setQ(e.target.value);setFiltersOpen(true);}}/></div><button onClick={()=>setFiltersOpen(true)} aria-label="検索とフィルターを開く"><SlidersHorizontal size={18}/></button></div>
      <div className="map-breadcrumb"><span>SETOUCHI ARCHIPELAGO</span><b>{selectedIsland?.name||'上島町'}</b></div>
      {!p&&<section className="welcome-card glass"><div className="eyebrow">A LITTLE CLOSER TO THE ISLANDS</div><h2>{selectedIsland?selectedIsland.name:'海を渡る。'}<br/>{selectedIsland?'の、その先へ。':'物語に出会う。'}</h2><p>{selectedIsland?.summary||'山の稜線、海辺の松林、島に残る記憶。地図の印をひとつ、ひらいてみませんか。'}</p><div className="welcome-counts"><div><b>{selectedIsland?visible.length:stats.verified}</b><span>確認済みの場所</span></div><div><b>8</b><span>めぐる島</span></div></div><button className="primary" disabled={!visible.length} onClick={()=>visible[0]&&select(visible[0].id)}>場所の物語をひらく <ArrowUpRight size={17}/></button>{selectedIsland&&<a className="text-link" href={selectedIsland.official_url} target="_blank" rel="noopener noreferrer">島の公式ガイド <ArrowUpRight size={13}/></a>}<div className="welcome-foot"><Compass size={15}/><span>地図から島名も選べます</span></div></section>}
      {p&&<section className={`detail-panel glass sheet-${sheet}`} aria-label="観光スポットの詳細">
        <button className="sheet-handle" onClick={()=>setSheet(sheet==='compact'?'detail':'compact')} aria-label="詳細パネルの高さを切り替え"><span/></button>
        <div className="detail-top"><span className="eyebrow">{islands.find(i=>i.name===p.island)?.english} · PLACE STORY</span><div><button className="icon-button" aria-label={`${p.name}をしおり${saved.includes(p.id)?'から削除':'に保存'}`} aria-pressed={saved.includes(p.id)} onClick={()=>toggleSave(p.id)}>{saved.includes(p.id)?<Check size={19}/>:<Bookmark size={19}/>}</button><button className="icon-button" onClick={closeDetail} aria-label="地点詳細を閉じる"><X size={20}/></button></div></div>
        <div className="detail-scroll" key={p.id}>
          <div className="detail-heading"><span className="place-number">{String(pois.indexOf(p)+1).padStart(2,'0')} <span>/ {String(stats.verified).padStart(2,'0')}</span></span><h2>{p.name}</h2><div className="place-meta"><MapPin size={13}/>{p.island}<span/> {p.categories[0].split(' / ')[0]}</div><p className="lead">{p.summary}</p></div>
          <div className="detail-tabs"><button className={!deep?'active':''} onClick={()=>{setDeep(false);setSheet('detail');}}>場所のこと</button><button className={deep?'active':''} onClick={()=>{setDeep(true);setSheet('deep');}}><BookOpen size={14}/> 深掘り <span>DEEP DIVE</span></button></div>
          {!deep?<><p className="description">{p.description}</p><div className="tag-row">{p.related_topics.slice(0,4).map(t=><button key={t} onClick={()=>{setTopic(t);setSelected(null);setQ('');setIsland('all');setCategory('all');setSavedOnly(false);}}>{t}<ArrowUpRight size={10}/></button>)}</div></>:<>
            <div className="deep-heading"><span className="eyebrow">THE STORY BEHIND THE PLACE</span><h3>この場所から、ひとつ深く。</h3><p>公式資料から読める物語をたどります。</p></div>
            {orderedSections(p.deep_dive,context).map((s,i)=><article className="deep-section" key={s.title}><span className="deep-index">{String(i+1).padStart(2,'0')}</span><h4>{s.title}</h4><p>{s.text}</p><a href={s.source_urls[0]} target="_blank" rel="noopener noreferrer">この記述の出典 <ArrowUpRight size={11}/></a></article>)}
            {p.related_people.length>0&&<div className="people"><span className="section-label">関わる人物</span>{p.related_people.map(name=><button key={name} onClick={()=>{setQ(name);closeDetail();}}>{name}<Search size={12}/></button>)}</div>}
            <div className="topic-graph"><span className="section-label">つながるテーマ</span><p>場所からテーマへ、テーマから次の場所へ。</p><div className="graph-center"><MapPin size={14}/>{p.name}</div><div className="graph-branches">{p.related_topics.map(t=><button key={t} onClick={()=>{setTopic(t);closeDetail();setQ('');setIsland('all');setCategory('all');setSavedOnly(false);}}>{t}<ChevronRight size={12}/></button>)}</div><div className="theme-next">{topics.find(t=>t.id===p.related_topics[0])?.related_topics.map(t=><button key={t} onClick={()=>{setTopic(t);closeDetail();setQ('');setIsland('all');setCategory('all');}}>さらに「{t}」へ <ArrowUpRight size={11}/></button>)}</div></div>
          </>}
          <section className="access-card"><div className="section-label"><TopicIcon size={15}/> ここへの行き方</div><div className="origin-options"><button className={originType==='port'?'active':''} onClick={()=>setOriginType('port')}>港から</button><button className={originType==='current'?'active':''} onClick={()=>{if(!origin)locate();else setOriginType('current');}}>現在地から</button></div><strong>{originType==='port'?(p.access.port||'島へのアクセス'):origin?'現在地からの外部案内':'現在地の取得が必要です'}</strong><p>{p.access.note}</p>{p.location_scope.includes('代表地点')&&<p className="coordinate-note">地図の印: {p.location_scope}</p>}{(mode==='ferry'||requiresFerry(undefined,p.island)||originType==='current')&&<div className="ferry-note"><Ship size={14}/><span>{p.island==='津波島'?'予約した渡船を利用します。':'島への移動には航路を利用する場合があります。'} 最新の運航・時刻表を確認してください。</span></div>}
          <div className="access-links"><a href={p.access.official_url} target="_blank" rel="noopener noreferrer">公式の航路・アクセス <ArrowUpRight size={13}/></a>{mode!=='ferry'&&p.access.modes.includes(mode)&&<a href={originType==='current'?directionsUrl(p,mode,origin):`${directionsUrl(p,mode)}${p.access.port?'&origin='+encodeURIComponent(p.access.port+' 上島町'):''}`} target="_blank" rel="noopener noreferrer">{modeNames[mode]}ルートを外部地図で確認 <ArrowUpRight size={13}/></a>}</div><small>案内確認日 {p.access.checked_at} · 所要時間は公式の目安</small></section>
          {p.warnings.length>0&&<div className="place-warning"><CircleHelp size={16}/><div>{p.warnings.map(w=><p key={w}>{w}</p>)}</div></div>}
          <section className="next-places"><div className="section-label">次に、どこへ。<span>FOR YOUR TRIP</span></div>{suggestions.map(({poi,reasons})=><button className="next-place" key={poi.id} onClick={()=>select(poi.id)}><div><small>{poi.island} · {reasons.slice(0,2).join(' / ')}</small><strong>{poi.name}</strong></div><ArrowUpRight size={17}/></button>)}</section>
          <details className="sources" open={deep}><summary><CheckCircle2 size={14}/>出典・確認情報 <ChevronDown size={14}/></summary><div><dl><dt>確認日</dt><dd>{p.last_verified_at}</dd><dt>状態</dt><dd>{p.verification_status==='official_verified'?'公式情報で確認':'複数の公式資料で照合'}</dd><dt>資料更新日</dt><dd>{p.content_date||'記載なし'}</dd><dt>地点について</dt><dd>{p.location_scope}</dd><dt>位置の出典</dt><dd>{p.coordinate_source}</dd></dl><div className="source-links">{p.source_urls.map((url,i)=><a key={url} href={url} target="_blank" rel="noopener noreferrer"><span>{i+1}. {new URL(url).hostname.includes('iyokannet')?'愛媛県公式観光':new URL(url).hostname.includes('gsi')?'国土地理院資料':'上島町公式観光'}</span><ArrowUpRight size={12}/></a>)}</div></div></details>
        </div>
        <div className="detail-footer"><CheckCircle2 size={12}/><span>確認日 {p.last_verified_at}</span><button onClick={share}>この場所を共有 <Share2 size={13}/></button></div>
      </section>}
      {!p&&<div className="journey-strip glass"><div className="journey-mark"><Compass size={23}/></div><div><span className="eyebrow">FOLLOW YOUR CURIOSITY</span><strong>{activeTopic?`「${activeTopic.name}」をたどる`:island==='all'?'まずは、ひとつの島から。':`${island}をゆっくりめぐる。`}</strong><small>{visible.length}の確認済み地点 · {modeNames[mode]}で探す{visible.length>=2?' · 左の一覧で次の場所を選べます':''}</small></div><button onClick={()=>setFiltersOpen(true)} aria-label="島と場所の一覧を表示"><ChevronRight size={20}/></button></div>}
      <button className="mobile-explore-toggle" onClick={()=>setFiltersOpen(true)}><Compass size={15}/>場所を探す <span>{visible.length}</span><ChevronUp size={14}/></button>
      <div className="map-status" role="status"><span className="status-dot"/>{status}<span className="status-divider"/>データ確認 {stats.checked_at}<button onClick={()=>setAbout(true)}>出典</button></div>
    </main>
    {toast&&<div className="toast" role="status">{toast}</div>}
    <dialog ref={dialog} onCancel={()=>setAbout(false)} onClick={e=>{if(e.target===dialog.current)setAbout(false);}}><div className="about-header"><span className="eyebrow">ABOUT THIS MAP</span><button className="icon-button" onClick={()=>setAbout(false)} aria-label="地図の説明を閉じる"><X size={21}/></button></div><h2>確認した場所から、<br/>島の物語を。</h2><p>上島町の観光を、地図と出典から探索する図鑑です。町の公式サービスではありません。</p><div className="audit-counts"><div><b>{stats.verified}</b><span>公開地点</span></div><div><b>{stats.pending}</b><span>未確認候補</span></div><div><b>8</b><span>主要島</span></div></div><p>公式一覧148件から調査し、景勝地・島の代表地点3件を追加しました。未確認地点は地図に載せません。紹介内容と位置の出典をそれぞれ記録しています。</p><p>3D地形は国土地理院DEMをTerrain RGBへ変換し、標高強調1.0で表示。海域などの無効値は表示用の0m平面で、測定標高ではありません。地形を読み込めない場合は2Dへ切り替えます。</p><p>建物の高さを確認できるデータは現在0件です。高さを仮定した建物表示はしていません。写真は公式サイトから無断転載せず、リンクで案内しています。</p><p>しおりはこのブラウザー内に保存されます。現在地はボタン操作時だけ取得し、保存しません。外部地図を開くと、そのサービスへ行き先と取得済みの現在地が渡されます。</p><div className="about-links"><a href="https://kamijima.info/" target="_blank" rel="noopener noreferrer">上島町公式観光ガイド <ArrowUpRight size={14}/></a><a href="https://kamijima.info/concerned/" target="_blank" rel="noopener noreferrer">2026年版パンフレット <ArrowUpRight size={14}/></a><a href={`${import.meta.env.BASE_URL}data/pois.geojson`} download>公開地点のGeoJSON <ArrowUpRight size={14}/></a></div><small>情報確認日 {stats.checked_at} · 営業・公開・船の運航は最新の公式情報を確認</small></dialog>
  </div>;
}
